version: '3.4'


services:
  mssql-db:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Q1w2e3r4
  patientsapi:
    container_name: patients-api
    image: ${DOCKER_REGISTRY-}patientsapi
    build:
      context: .
      dockerfile: PatientsAPI/Dockerfile
    depends_on:
      - mssql-db
    ports: 
      - 80:80
    environment:
      - DB_HOST=mssql-db
      - DB_NAME=patient
      - DB_SA_PASSWORD=Q1w2e3r4
      - ASPNETCORE_ENVIRONMENT=Development